services:
  postgres:
    image: postgres:15-alpine
    container_name: pythia-postgres
    environment:
      POSTGRES_USER: pythia
      POSTGRES_PASSWORD: pythia_password
      POSTGRES_DB: pythiadb
    volumes:
      - pythia_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: pythia-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  pythia:
    build: .
    image: pythia:dev
    container_name: pythia
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PYTHIA_DATABASE_URL: "postgresql://pythia:pythia_password@postgres:5432/pythiadb"
      PYTHIA_CELERY_BROKER_URL: "redis://redis:6379/0"
      PYTHIA_CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ./data:/app/data      # sigma rules, yara rules, seed data
    restart: unless-stopped

  celery_worker:
    build: .
    image: pythia:dev
    container_name: pythia-celery
    command: celery -A pythia.core.celery_app.celery_app worker --loglevel=info
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      PYTHIA_DATABASE_URL: "postgresql://pythia:pythia_password@postgres:5432/pythiadb"
      PYTHIA_CELERY_BROKER_URL: "redis://redis:6379/0"
      PYTHIA_CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  pythia_pgdata:
